# Generated by Django 6.0.5 on 2026-05-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "Пользователь с таким email уже существует."},
                max_length=254,
                unique=True,
                verbose_name="Email",
            ),
        ),
    ]
