# Generated by Django 6.0.5 on 2026-05-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
        ),
    ]
