# Generated by Django 6.0.5 on 2026-06-23 16:44

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supervision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "supervision_type",
                    models.CharField(
                        choices=[("individual", "Индивидуальная"), ("group", "Групповая")],
                        max_length=20,
                        verbose_name="Тип супервизии",
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Для групповой супервизии укажите >1",
                        verbose_name="Максимальное количество участников",
                    ),
                ),
                ("start_datetime", models.DateTimeField(verbose_name="Дата и время начала")),
                ("end_datetime", models.DateTimeField(verbose_name="Дата и время окончания")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Цена")),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Открыта"), ("cancelled", "Отменена"), ("completed", "Завершена")],
                        default="open",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "psychologist",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ведущий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Супервизия",
                "verbose_name_plural": "Супервизии",
                "ordering": ["-start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="SupervisionRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="ФИО")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Телефон"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="Email")),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "Новая"), ("processed", "Обработана"), ("cancelled", "Отменена")],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supervision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="consultations.supervision",
                        verbose_name="Супервизия",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervision_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на супервизию",
                "verbose_name_plural": "Заявки на супервизию",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TherapySession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("start_datetime", models.DateTimeField(verbose_name="Дата и время начала")),
                ("end_datetime", models.DateTimeField(verbose_name="Дата и время окончания")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Цена")),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Открыта"), ("cancelled", "Отменена"), ("completed", "Завершена")],
                        default="open",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "psychologist",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapy_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Психолог",
                    ),
                ),
            ],
            options={
                "verbose_name": "Терапевтическая сессия",
                "verbose_name_plural": "Терапевтические сессии",
                "ordering": ["-start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="TherapyRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="ФИО")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Телефон"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="Email")),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "Новая"), ("processed", "Обработана"), ("cancelled", "Отменена")],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="therapy_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="consultations.therapysession",
                        verbose_name="Сессия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на терапию",
                "verbose_name_plural": "Заявки на терапию",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupervisionBooking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("confirmed", "Подтверждена"), ("cancelled", "Отменена")],
                        default="confirmed",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("booked_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата записи")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervision_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Студент",
                    ),
                ),
                (
                    "supervision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="consultations.supervision",
                        verbose_name="Супервизия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись на супервизию",
                "verbose_name_plural": "Записи на супервизию",
                "ordering": ["-booked_at"],
                "unique_together": {("student", "supervision")},
            },
        ),
        migrations.CreateModel(
            name="TherapyBooking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("confirmed", "Подтверждена"), ("cancelled", "Отменена")],
                        default="confirmed",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("booked_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата записи")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapy_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Студент",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="consultations.therapysession",
                        verbose_name="Сессия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись на терапию",
                "verbose_name_plural": "Записи на терапию",
                "ordering": ["-booked_at"],
                "unique_together": {("student", "session")},
            },
        ),
    ]
