# Generated by Django 6.0.5 on 2026-05-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choice",
            options={
                "ordering": ["question", "id"],
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответов",
            },
        ),
        migrations.AlterModelOptions(
            name="test",
            options={"ordering": ["lesson__order"], "verbose_name": "Тест", "verbose_name_plural": "Тесты"},
        ),
    ]
