# Generated by Django 6.0.5 on 2026-06-22 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_choice_options_alter_test_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Название категории")),
                ("slug", models.SlugField(unique=True, verbose_name="URL-идентификатор")),
                (
                    "space_type",
                    models.CharField(
                        choices=[
                            ("family", "Пространство семьи"),
                            ("academy", "Академия системного консультирования"),
                        ],
                        max_length=20,
                        verbose_name="Пространство",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("is_active", models.BooleanField(default=True, verbose_name="Отображать")),
            ],
            options={
                "verbose_name": "Категория курсов",
                "verbose_name_plural": "Категории курсов",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="required_courses",
            field=models.ManyToManyField(
                blank=True,
                help_text="Курсы, которые должны быть завершены до записи на этот курс (направленная связь).",
                related_name="required_for",
                to="courses.course",
                verbose_name="Обязательные курса для доступа",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата завершения"),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="Курс завершён"),
        ),
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="courses.coursecategory",
                verbose_name="Категория",
            ),
        ),
    ]
